[build]
  functions = "functions"
  [functions]
node_bundler = "esbuild" # o "webpack" si prefieres
node_version = "16"      # O la versión soportada por Netlify

[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true
