[build]
functions = "functions"

[functions]
directory = "/netlify/functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

  
[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true
