[build]
functions = "functions"
command = "npm install && npm run build"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

  
[[redirects]]
  from = "/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true
